# Generated by Django 3.0.5 on 2020-05-22 20:00

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Quiz ID')),
                ('title', models.CharField(max_length=256, verbose_name='Quiz Title')),
                ('slug', models.SlugField(blank=True, max_length=256, verbose_name='Slug')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('level', models.CharField(choices=[(None, ''), ('fluent', 'Fluent/Native Speaker'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], max_length=128, verbose_name='French Level')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='quiz/thumbnails/')),
                ('cost', models.IntegerField(default=0, verbose_name='Quiz Cost')),
                ('total_time', models.DurationField(default=datetime.timedelta(seconds=900), verbose_name='Total Time')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Quiz Created On')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_on'],
            },
        ),
    ]
