# Generated by Django 3.0.5 on 2020-05-26 12:42

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Quiz ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField()),
                ('explanation', ckeditor_uploader.fields.RichTextUploadingField()),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('bool', 'True or False'), ('text', 'Text Answer')], max_length=32)),
                ('options', models.CharField(max_length=1024, null=True)),
                ('answer', models.CharField(max_length=32)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_on'],
            },
        ),
    ]
