# Generated by Django 3.0.7 on 2020-06-20 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.Competition'),
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together={('user', 'quiz', 'competition')},
        ),
    ]
