# Generated by Django 3.0.5 on 2020-06-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=32, verbose_name='Answer: any of the following: T, F, 1, 2, 3, 4 or some text  '),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
