# Generated by Django 3.0.5 on 2020-05-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
