# Generated by Django 3.0.5 on 2020-06-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200616_0324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
