# Generated by Django 3.1 on 2020-09-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200915_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='submission',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
