# Generated by Django 3.1 on 2021-01-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200915_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[(None, ''), ('fluent', 'Fluent/Native Speaker'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner'), ('any', 'French Learner of any Level')], max_length=128, verbose_name='French Level'),
        ),
    ]
