# Generated by Django 3.0.5 on 2020-06-16 12:42

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0006_quizaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='user',
            field=models.ForeignKey(default='paramkpr', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='submission',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='submit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
