# Generated by Django 3.0.5 on 2020-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200616_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='correct_answers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='incorrect_answers',
            field=models.IntegerField(null=True),
        ),
    ]
