# Generated by Django 3.0.5 on 2020-05-26 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(max_length=1024)),
                ('zoom_link', models.CharField(max_length=1024)),
                ('cost', models.IntegerField()),
                ('discount', models.IntegerField(verbose_name='Discount Percentage')),
                ('date', models.DateTimeField()),
                ('include_book', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'ordering': ['-created_on'],
            },
        ),
    ]
