# Generated by Django 3.0.5 on 2020-05-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='zoom_link',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
