# Generated by Django 3.0.5 on 2020-05-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20200527_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Workshop Id'),
        ),
    ]
