# Generated by Django 3.0.5 on 2020-06-06 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_workshop_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('zoom_link', models.URLField(verbose_name='Link to Zoom Session')),
                ('date', models.DateTimeField(verbose_name='Date of this Session')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Workshop Session',
                'verbose_name_plural': 'Workshop Sessions',
            },
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='zoom_link',
        ),
        migrations.AddField(
            model_name='workshop',
            name='sessions',
            field=models.ManyToManyField(related_name='workshop_sessions', to='workshops.Session'),
        ),
    ]
