# Generated by Django 3.0.5 on 2020-06-06 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('workshops', '0006_auto_20200606_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-created_on',), 'verbose_name': 'Workshop Session', 'verbose_name_plural': 'Workshop Sessions'},
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('uses', models.IntegerField()),
                ('expiry_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.Workshop')),
            ],
            options={
                'verbose_name': 'Workshop Code',
                'verbose_name_plural': 'Workshop Codes',
                'ordering': ('workshop', '-created_on'),
            },
        ),
    ]
