# Generated by Django 3.0.5 on 2020-06-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_auto_20200606_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ('-created_on',), 'verbose_name': 'Workshop Code', 'verbose_name_plural': 'Workshop Codes'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('date',), 'verbose_name': 'Workshop Session', 'verbose_name_plural': 'Workshop Sessions'},
        ),
    ]
