# Generated by Django 3.0.7 on 2020-06-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_auto_20200616_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='thumbnail',
            field=models.ImageField(blank=True, default='workshops/thumbnails/default_workshop.png', upload_to='workshops/thumbnails/'),
        ),
    ]
