# Generated by Django 3.1 on 2020-11-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0012_workshopcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube Video'),
        ),
    ]
