# Generated by Django 3.1 on 2020-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0013_workshop_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='video',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Youtube Video ID'),
        ),
    ]
