# Generated by Django 3.1 on 2021-01-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0014_auto_20201128_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='not_for_sale',
            field=models.BooleanField(default=False, verbose_name='Not For Sale'),
        ),
    ]
