# Generated by Django 3.1 on 2021-01-03 10:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0015_workshop_not_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
