# Generated by Django 3.0.5 on 2020-05-18 11:28

from django.db import migrations, models
import sorobrain.media_storages


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_notification_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=sorobrain.media_storages.PrivateMediaStorage(), upload_to='user_data/avatars'),
        ),
    ]
