# Generated by Django 3.0.7 on 2020-06-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0017_auto_20200619_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('quiz', 'workshop', 'competition')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
