# Generated by Django 3.0.7 on 2020-07-01 06:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200620_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOnOneClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=256, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('cost', models.IntegerField(help_text='Per class cost')),
                ('duo_cost', models.IntegerField(help_text='The cost for two people taking a class together, per class')),
                ('level', models.CharField(choices=[(None, ''), ('fluent', 'Fluent/Native Speaker'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], max_length=128, verbose_name='French Level')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'One on One Class',
                'verbose_name_plural': 'One on One Classes',
            },
        ),
    ]
