# Generated by Django 3.1 on 2020-11-21 04:54

from django.db import migrations, models
import sorobrain.media_storages


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.ImageField(blank=True, null=True, storage=sorobrain.media_storages.PrivateMediaStorage(), upload_to='user_data/school_ids/'),
        ),
    ]
