# Generated by Django 3.1 on 2020-11-28 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_user_school_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=140, unique=True, verbose_name='Code')),
                ('referrer_incentive', models.IntegerField(default=50, verbose_name='Referrer Incentive')),
                ('referee_incentive', models.IntegerField(default=50, verbose_name='Referee Incentive')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Referrer')),
                ('used_by', models.ManyToManyField(related_name='referee', to=settings.AUTH_USER_MODEL, verbose_name='Used By')),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
            },
        ),
    ]
