# Generated by Django 3.1 on 2020-11-28 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_referralcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='referrer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Referrer'),
        ),
    ]
