# Generated by Django 3.1 on 2020-11-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201128_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='redeemed',
            field=models.BooleanField(default=False, verbose_name='Redeemed'),
        ),
    ]
