# Generated by Django 3.1 on 2021-01-03 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
