# Generated by Django 3.0.7 on 2020-06-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20200620_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionquiz',
            options={'ordering': ('-created_on',), 'verbose_name': 'Competition Quiz', 'verbose_name_plural': 'Competition Quizzes'},
        ),
    ]
