# Generated by Django 3.1 on 2020-08-26 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0005_competitioncertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='include_book',
            field=models.BooleanField(default=False, verbose_name='Include Book'),
        ),
        migrations.AlterUniqueTogether(
            name='competitioncertificate',
            unique_together={('user', 'competition')},
        ),
    ]
