# Generated by Django 3.1 on 2021-01-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_competition_hide_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='level',
            field=models.CharField(choices=[(None, ''), ('fluent', 'Fluent/Native Speaker'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner'), ('any', 'French Learner of any level')], max_length=128, verbose_name='French Level'),
        ),
    ]
