# Generated by Django 3.1 on 2021-01-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_auto_20210103_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='rank_limit',
            field=models.IntegerField(default=25),
        ),
    ]
