# Generated by Django 3.1 on 2021-01-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_competition_not_for_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='rank_limit',
            new_name='certificate_rank_limit',
        ),
        migrations.AddField(
            model_name='competition',
            name='leaderboard_rank_limit',
            field=models.IntegerField(default=25),
        ),
    ]
